// Common action types
export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT',
} as const

// Authentication action types
export const AUTH_ACTION_TYPES = {
  LOGIN: 'AUTH_LOGIN',
  REGISTER: 'AUTH_REGISTER',
  LOGOUT: 'AUTH_LOGOUT',
  FETCH_PROFILE: 'AUTH_FETCH_PROFILE',
  UPDATE_PROFILE: 'AUTH_UPDATE_PROFILE',
  CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
} as const

//isuue action types
export const ISSUE_ACTION_TYPES = {
  FETCH_ISSUES: 'ISSUE_FETCH_ISSUES',
  FETCH_ISSUE: 'ISSUE_FETCH_ISSUE',
  CREATE_ISSUE: 'ISSUE_CREATE_ISSUE',
  UPDATE_ISSUE: 'ISSUE_UPDATE_ISSUE',
  DELETE_ISSUE: 'ISSUE_DELETE_ISSUE',
  FETCH_STATUS_COUNTS: 'ISSUE_FETCH_STATUS_COUNTS',
  CLEAR_CURRENT_ISSUE: 'ISSUE_CLEAR_CURRENT_ISSUE',
  FETCH_METADATA: 'ISSUE_FETCH_METADATA',
  FETCH_MY_ISSUES: 'ISSUE_FETCH_MY_ISSUES',
  FETCH_MY_STATUS_COUNTS: 'ISSUE_FETCH_MY_STATUS_COUNTS',
  CLEAR_ERROR: 'ISSUE_CLEAR_ERROR',
} as const

// User management action types (Admin)
export const USER_ACTION_TYPES = {
  FETCH_USERS: 'USER_FETCH_USERS',
  FETCH_USER: 'USER_FETCH_USER',
  DELETE_USER: 'USER_DELETE_USER',
  ENABLE_USER: 'USER_ENABLE_USER',
  PERMANENT_DELETE_USER: 'USER_PERMANENT_DELETE_USER',
  CLEAR_ERROR: 'USER_CLEAR_ERROR',
} as const

// Export/Report action types
export const EXPORT_ACTION_TYPES = {
  DOWNLOAD_REPORT: 'EXPORT_DOWNLOAD_REPORT',
} as const
